[package]
name = "minpty"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["async"] }
napi-derive = "2"
portable-pty = "0.7"
anyhow = "1.0"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
