/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function spawn(cmd: string, args: Array<string>, onDataCb: (...args: any[]) => any, onExitCb: (...args: any[]) => any): void
