name: minpty CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CI
        uses: devcontainers/ci@v0.2
        with:
          runCmd: yarn && yarn ci